### ISSUE TITLE
Clean example of routing depending on method (GET, POST)

### ISSUE THREAD

**Issue by marlun** [Matt-Esch/http-hash#3]
I understand that this is outside of what this module is supposed to do but I'm not sure where else to ask this and this module should at least be involved.

How would you use this together with something else to run different functions depending on the HTTP method? For example if I want different handlers for GET /contacts and POST /contacts where one delivers all the contacts and the other adds a new contact?

**Comment by javierjmx** [comment]
https://github.com/Matt-Esch/http-hash-router

**Comment by marlun** [comment]
Are you telling me that URL has an example because then I'm not seeing it?

**Comment by javierjmx** [comment]
Well, it does not have an example, but it tells you that

> .set() takes a route pattern and a route handler. A route handler is either a function or an object. If you use an object then we will create a route handler function using the http-methods module.

So, if you take a look at https://github.com/Matt-Esch/http-hash-router/blob/master/test/index.js on line 125, you can see a working axample.

**Comment by marlun** [comment]
I see :smiley: I honestly didn't make it to that sentence because it didn't seem to be what I was after at all. Thanks @elMauNunez for taking time to explain it!
